version: '3.8'

services:
  minsait-challenge:
    build: .
    image: challenge:latest
    environment:
      MONGO_USER: admin
      MONGO_PASS: secret
      MONGO_PORT: 27017
      MONGO_HOST: mongodb
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'
    networks:
      - network

networks:
  network:
    driver: bridge